### ISSUE TITLE
仓库里缺少sql文件，本地无法正常拉起服务

### ISSUE THREAD

**Issue by zhuima** [noovertime7/gin-mysqlbak#2]
文档里的描述：
将工程内sql文件夹下的init_3.0.0.sql拷贝至mysql主机根目录下

当前版本仍需要手动刷入sql文件，自动初始化数据库将在3.0.1支持

尝试操作：
1、当前clone的是main分支，看对应版本是3.0.3，但是并没有进行AutoMigrate操作
2、直接下载release代码，也没有进行AutoMigrate

**Comment by noovertime7** [comment]
不好意思，我更新一下最新的sql文件，目前server端因为最近工作忙还没有加上AutoMigrate，agent端是有的

**Comment by noovertime7** [comment]
请参阅 53577389f80ecff0ff16df456327e186d6e0e2fe

**Comment by lizhen789** [comment]
没有用户数据，无法登录

**Comment by noovertime7** [comment]
非常抱歉，目前正在研发新的备份平台，下半年应该会开源出来，这个项目暂时不更新了
![jpg](http://qiniu.yunxue521.top/461690523534_.pic.jpg)
